### ISSUE TITLE
Uncaught error at user-stream.js

### ISSUE THREAD

**Issue by cyberdie** [Blastitt/twitControl#1]
Hi. I'm suffering this error. No tweets at all in the mirror.
It looks like internet connection error but there are more internet connected modules working without issues. Even restarting the app when RPi is running some minutes (connection established correctly) fails with same error

`{ Error: Uncaught, unspecified "error" event. ([object Object])
    at Stream.emit (events.js:163:17)
    at ClientRequest.<anonymous> (/home/pi/MagicMirror/node_modules/user-stream/                                                                                        lib/user-stream.js:173:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:306:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  context:
   { type: 'request',
     data:
      { Error: socket hang up
          at TLSSocket.onHangUp (_tls_wrap.js:1087:19)
          at TLSSocket.g (events.js:286:16)
          at emitNone (events.js:91:20)
          at TLSSocket.emit (events.js:185:7)
          at endReadableNT (_stream_readable.js:926:12)
          at _combinedTickCallback (internal/process/next_tick.js:74:11)
          at process._tickCallback (internal/process/next_tick.js:98:9) code: 'E                                                                                        CONNRESET' } } }
`

**Comment by Blastitt** [comment]
That error looks like it has to do with the external dependency [user-stream](https://github.com/aivis/user-stream). Make sure your auth token credentials are set correctly and you have a good internet connection. If it still doesn't work, you'll have to seek more support from that repo.
